spring:
  datasource:
    url: jdbc:h2:mem:database
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2console

  jpa:
    show-sql: true
    defer-datasource-initialization: true

#resilience4j:
#  circuitbreaker:
#    instances:
#      service1:
#        registerHealthIndicator: true
#        ringBufferSizeInClosedState: 5
#        ringBufferSizeInHalfOpenState: 3
#        waitDurationInOpenState: 10s
#        failureRateThreshold: 50
#        recordExceptions:
#          - org.springframework.web.client.HttpServerErrorException
#          - java.io.IOException
#          - java.util.concurrent.TimeoutException
#          - org.springframework.web.client.ResourceAccessException

#resilience4j:
#  circuitbreaker:
#    configs:
#      shared:
#        register-health-indicator: true
#        sliding-window-type: count_based
#        sliding-window-size: 5
#        failure-rate-threshold: 40
#        slow-call-rate-threshold: 40
#        permitted-number-of-calls-in-half-open-state: 1
#        max-wait-duration-in-half-open-state: 10s
#        wait-duration-in-open-state: 10s
#        slow-call-duration-threshold: 2s
#        writable-stack-trace-enabled: true
#        automatic-transition-from-open-to-half-open-enabled: true
#    instances:
#      example:
#        base-config: shared

resilience4j:
  circuitbreaker:
    instances:
      CBBasketballLiveMatches:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10